### ISSUE TITLE
Notebook cleanup and binder for public demo?

### ISSUE THREAD

**Issue by rabernat** [mfreilich1/cmip6hack-ocean-bgc#35]
Hi CMIP6 Hackers!

We are beginning to think about how to collect and share all of the amazing work that happened at the CMIP6 hackathon. Google will announce the CMIP6 public data program on Dec. 2, and we'd like to have some examples to share with the world by that time. We have identified your project as one of the ones we'd like to include in an examples gallery.

What we'd like to see happen are the following:
- [x] pick ONE notebook as representative of your project and clean it up so that it can execute in sequence with no errors. (It doesn't have to be the most complex or ambitious thing--just something that loads and visualizes some of the data is more than sufficient.)
- [x] create a binder using http://binder.pangeo.io/ (we can help with the details on this)
- [x] use Zenodo to [make your repo citable](https://guides.github.com/activities/citable-code/) to ensure you get proper attribution.

We're really excited about your project and hope you can find some time to work with us to get these items completed by the target date.

**Comment by mara-freilich** [comment]
Thanks for letting us know! We'll coordinate a share a binder with you before December 2nd.

**Comment by jbusecke** [comment]
@rabernat, we are currently prepping that notebook, but some of the analyses need quite a bit of computing time. Would the output be expected to run on the binder (e.g. can we link to the kubernetes dask clusters somehow?) and if that is possible should we aim for a maximum execution time?

**Comment by mara-freilich** [comment]
@rabernat We created a binder and the repository is now citable. Let us know if there is anything else that you need for the announcement of the public data program
