### ISSUE TITLE
Preformed vs Regenerated carbon

### ISSUE THREAD

**Issue by seamanticscience** [mfreilich1/cmip6hack-ocean-bgc#6]

**Comment by jbusecke** [comment]
Could you explain how to do this calculation from clip available output? I could try to help. Cheers

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seamanticscience** [comment]
From `UKESM1-0-LL.historical`

![download](https://user-images.githubusercontent.com/26678243/67050559-c9d83b80-f106-11e9-8910-80daef2ec82d.png)

**Comment by seamanticscience** [comment]
See `notebooks/jml_dissic_prereg.ipynb` and `notebooks/jml_dissic_prereg_allmodels.ipynb` for examples of total dissolved, preformed, and regenerated carbon calculations and linear trends over the historical period (1850-2014).

![download-1](https://user-images.githubusercontent.com/26678243/67613310-f7159100-f779-11e9-9403-91caa87730b1.png)
