### ISSUE TITLE
global maps and trends in heat and air-sea CO2 flux

### ISSUE THREAD

**Issue by pedmondlerner** [mfreilich1/cmip6hack-ocean-bgc#7]
i. map the mean air-sea CO2 and heat flux in different models.
ii. map the change in air-sea and heat fluxes between beginning and end of historical period in different models.
iii. Plot the multi-model global heat and CO2 flux (in Pg C/yr).

**Comment by pedmondlerner** [comment]
These are tasks I am planning to complete today/tomorow

**Comment by jbusecke** [comment]
I tried to compute heat content yesterday and have a (perhaps stupid) question. We would need to multiply (temp*cp*vol*rho) to get heat content for each cell, right? 

Is that temperature in situ or potential?

Should we calaculate the heat capacity based on (T/S/p)?

Do all the models have the same reference density? I assume they are all Boussinesque?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment]
Going ahead and closing this.
